// <auto-generated />
using System;
using Apcloudpms.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apcloudpms.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ApplicationModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("ApplicationModule", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PERMIT",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage permit applications, reviews, and approvals.",
                            DisplayOrder = 1,
                            Icon = "file-check",
                            IsActive = true,
                            Name = "Permit Management System"
                        },
                        new
                        {
                            Id = 2,
                            Code = "VISITOR",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage visitor registration, check-in, and visit history.",
                            DisplayOrder = 2,
                            Icon = "users",
                            IsActive = true,
                            Name = "Visitor Management System"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ASSET",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage organizational assets and assignments.",
                            DisplayOrder = 3,
                            Icon = "package",
                            IsActive = true,
                            Name = "Asset Management System"
                        },
                        new
                        {
                            Id = 4,
                            Code = "POWERBI",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View embedded Power BI dashboards and reports.",
                            DisplayOrder = 4,
                            Icon = "bar-chart",
                            IsActive = true,
                            Name = "Analytics and Reports"
                        });
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ApprovalNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("PermitApprovalId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PermitApprovalId", "RecipientUserId")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.HasIndex("RecipientUserId", "ReadAtUtc", "CreatedAtUtc");

                    b.ToTable("ApprovalNotification", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PermitTypeListItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PermitTypeListItemId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("ApprovalWorkflow", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ApprovalWorkflowLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlternateApproverRoleId")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalWorkflowId")
                        .HasColumnType("int");

                    b.Property<byte>("LevelNumber")
                        .HasColumnType("tinyint");

                    b.Property<int>("PrimaryApproverRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlternateApproverRoleId");

                    b.HasIndex("PrimaryApproverRoleId");

                    b.HasIndex("ApprovalWorkflowId", "LevelNumber")
                        .IsUnique();

                    b.ToTable("ApprovalWorkflowLevel", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalWorkflowLevel_LevelNumber", "[LevelNumber] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId", "ChangedAtUtc");

                    b.HasIndex("EntityName", "ChangedAtUtc");

                    b.ToTable("AuditLog", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OfficeBranchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfficeBranchId", "Code")
                        .IsUnique();

                    b.HasIndex("OfficeBranchId", "IsActive");

                    b.ToTable("Department", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ListItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SystemName");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsVisible");

                    b.Property<int>("ListItemCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ItemName");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("ListItemCategoryId", "Code")
                        .IsUnique();

                    b.HasIndex("ListItemCategoryId", "IsActive", "DisplayOrder");

                    b.ToTable("ListItem", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DRAFT",
                            CreatedAtUtc = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            ListItemCategoryId = 1,
                            Name = "Draft"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SUBMITTED_FOR_APPROVAL",
                            CreatedAtUtc = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            ListItemCategoryId = 1,
                            Name = "Submitted For Approval"
                        },
                        new
                        {
                            Id = 3,
                            Code = "APPROVED",
                            CreatedAtUtc = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            ListItemCategoryId = 1,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 4,
                            Code = "REJECTED",
                            CreatedAtUtc = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            ListItemCategoryId = 1,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 5,
                            Code = "DELETED",
                            CreatedAtUtc = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            ListItemCategoryId = 1,
                            Name = "Deleted"
                        });
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ListItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ListItemCategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CategoryName");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ListItemCategory", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PERMIT_STATUS",
                            CreatedAtUtc = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Workflow statuses for permit applications.",
                            IsActive = true,
                            Name = "Permit Status"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PERMIT_TYPE",
                            CreatedAtUtc = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Available permit application types.",
                            IsActive = true,
                            Name = "Permit Type"
                        });
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ModuleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ApplicationModuleId")
                        .HasColumnType("int");

                    b.Property<string>("ControllerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("int");

                    b.Property<string>("QueryUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ParentMenuId");

                    b.HasIndex("ApplicationModuleId", "QueryUrl")
                        .IsUnique()
                        .HasFilter("[QueryUrl] IS NOT NULL");

                    b.HasIndex("ApplicationModuleId", "IsActive", "DisplayOrder");

                    b.ToTable("ModuleMenu", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionName = "Index",
                            ApplicationModuleId = 1,
                            ControllerName = "PermitDashboard",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Icon = "dashboard",
                            IsActive = true,
                            Name = "Dashboard",
                            QueryUrl = "/api/permit/dashboard"
                        },
                        new
                        {
                            Id = 2,
                            ActionName = "Index",
                            ApplicationModuleId = 1,
                            ControllerName = "PermitApplications",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Icon = "file-text",
                            IsActive = true,
                            Name = "Permit Applications",
                            QueryUrl = "/api/permit/applications"
                        },
                        new
                        {
                            Id = 3,
                            ActionName = "Index",
                            ApplicationModuleId = 1,
                            ControllerName = "PermitApprovals",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Icon = "check-circle",
                            IsActive = true,
                            Name = "Permit Approvals",
                            QueryUrl = "/api/permit/approvals"
                        },
                        new
                        {
                            Id = 4,
                            ActionName = "Index",
                            ApplicationModuleId = 2,
                            ControllerName = "VisitorDashboard",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Icon = "dashboard",
                            IsActive = true,
                            Name = "Dashboard",
                            QueryUrl = "/api/visitor/dashboard"
                        },
                        new
                        {
                            Id = 5,
                            ActionName = "Index",
                            ApplicationModuleId = 2,
                            ControllerName = "VisitorCheckIn",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Icon = "log-in",
                            IsActive = true,
                            Name = "Visitor Check-In",
                            QueryUrl = "/api/visitor/check-in"
                        },
                        new
                        {
                            Id = 6,
                            ActionName = "Index",
                            ApplicationModuleId = 2,
                            ControllerName = "VisitorLog",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Icon = "list",
                            IsActive = true,
                            Name = "Visitor Log",
                            QueryUrl = "/api/visitor/log"
                        },
                        new
                        {
                            Id = 7,
                            ActionName = "Index",
                            ApplicationModuleId = 3,
                            ControllerName = "AssetDashboard",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Icon = "dashboard",
                            IsActive = true,
                            Name = "Dashboard",
                            QueryUrl = "/api/asset/dashboard"
                        },
                        new
                        {
                            Id = 8,
                            ActionName = "Index",
                            ApplicationModuleId = 3,
                            ControllerName = "AssetRegister",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Icon = "archive",
                            IsActive = true,
                            Name = "Asset Register",
                            QueryUrl = "/api/asset/register"
                        },
                        new
                        {
                            Id = 9,
                            ActionName = "Index",
                            ApplicationModuleId = 3,
                            ControllerName = "AssetAssignments",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Icon = "user-check",
                            IsActive = true,
                            Name = "Asset Assignments",
                            QueryUrl = "/api/asset/assignments"
                        },
                        new
                        {
                            Id = 10,
                            ActionName = "GetEmbedConfig",
                            ApplicationModuleId = 4,
                            ControllerName = "PowerBi",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Icon = "bar-chart-2",
                            IsActive = true,
                            Name = "Power BI Report",
                            QueryUrl = "/api/power-bi/embed-config"
                        });
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.OfficeBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHeadOffice")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsHeadOffice")
                        .IsUnique()
                        .HasFilter("[IsHeadOffice] = 1 AND [IsActive] = 1");

                    b.HasIndex("OrganizationId", "IsActive");

                    b.ToTable("OfficeBranch", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "Name");

                    b.ToTable("Organization", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("CancelledBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CancelledRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CompletionApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletionDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CompletionOfWorks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompletionRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("PermitIssuerContactNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PermitIssuerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PermitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermitReceiverContactNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PermitReceiverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PermitStatusListItemId")
                        .HasColumnType("int");

                    b.Property<int>("PermitTypeListItemId")
                        .HasColumnType("int");

                    b.Property<string>("PreRiskAssessmentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RiskAssessmentId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkHeightBelowSurface")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WorkLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PermitNumber")
                        .IsUnique();

                    b.HasIndex("PermitTypeListItemId");

                    b.HasIndex("RiskAssessmentId");

                    b.HasIndex("PermitStatusListItemId", "CreatedAtUtc");

                    b.ToTable("PermitApplication", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApplicationConfinedSpace", b =>
                {
                    b.Property<long>("PermitApplicationId")
                        .HasColumnType("bigint");

                    b.Property<int>("WorkingInConfinedSpaceListItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PermitApplicationId", "WorkingInConfinedSpaceListItemId");

                    b.HasIndex("WorkingInConfinedSpaceListItemId");

                    b.ToTable("PermitApplicationConfinedSpace", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApplicationInspectionPriorToComm", b =>
                {
                    b.Property<long>("PermitApplicationId")
                        .HasColumnType("bigint");

                    b.Property<int>("InspectionPriorToCommListItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PermitApplicationId", "InspectionPriorToCommListItemId");

                    b.HasIndex("InspectionPriorToCommListItemId");

                    b.ToTable("PermitApplicationInspectionPriorToComm", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApplicationWallWorks", b =>
                {
                    b.Property<long>("PermitApplicationId")
                        .HasColumnType("bigint");

                    b.Property<int>("WorksonWallListItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PermitApplicationId", "WorksonWallListItemId");

                    b.HasIndex("WorksonWallListItemId");

                    b.ToTable("PermitApplicationWallWorks", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApproval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActionedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ActionedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("AlternateApproverRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<byte>("LevelNumber")
                        .HasColumnType("tinyint");

                    b.Property<long>("PermitApplicationId")
                        .HasColumnType("bigint");

                    b.Property<int>("PrimaryApproverRoleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ActionedByUserId");

                    b.HasIndex("AlternateApproverRoleId");

                    b.HasIndex("PrimaryApproverRoleId");

                    b.HasIndex("PermitApplicationId", "LevelNumber")
                        .IsUnique();

                    b.HasIndex("Status", "AlternateApproverRoleId");

                    b.HasIndex("Status", "PrimaryApproverRoleId");

                    b.ToTable("PermitApproval", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_PermitApproval_LevelNumber", "[LevelNumber] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApprovalAssignee", b =>
                {
                    b.Property<long>("PermitApprovalId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("RevokedByUserId")
                        .HasColumnType("int");

                    b.HasKey("PermitApprovalId", "UserId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("UserId", "IsActive", "PermitApprovalId");

                    b.ToTable("PermitApprovalAssignee", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("char(64)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("SessionExpiresAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("FamilyId", "RevokedAtUtc");

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RiskAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaResponsibleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionOfWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("LocationOfWork")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("OtherEquipmentsPPE")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OtherProtectionMeasures")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PermitIssuerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermitReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PlannedEndDateTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("PlannedStartDateTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("PreRiskAssessmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RiskAssessmentStatusListItemId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("RiskAssessmentStatusListItemId", "CreatedAtUtc");

                    b.ToTable("RiskAssessment", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RiskAssessmentAdditionalPpe", b =>
                {
                    b.Property<int>("RiskAssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalProtectiveMeasuresListItemId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.HasKey("RiskAssessmentId", "AdditionalProtectiveMeasuresListItemId");

                    b.HasIndex("AdditionalProtectiveMeasuresListItemId");

                    b.ToTable("RiskAssessmentAdditionalPPE", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RiskAssessmentHazardCategory", b =>
                {
                    b.Property<int>("RiskAssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("HazardCategoriesListItemId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.HasKey("RiskAssessmentId", "HazardCategoriesListItemId");

                    b.HasIndex("HazardCategoriesListItemId");

                    b.ToTable("RiskAssessmentHazardCategories", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RiskAssessmentPpe", b =>
                {
                    b.Property<int>("RiskAssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialPermitListItemId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.HasKey("RiskAssessmentId", "SpecialPermitListItemId");

                    b.HasIndex("SpecialPermitListItemId");

                    b.ToTable("RiskAssessmentPPE", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RiskAssessmentSpecialPermit", b =>
                {
                    b.Property<int>("RiskAssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialPermitListItemId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.HasKey("RiskAssessmentId", "SpecialPermitListItemId");

                    b.HasIndex("SpecialPermitListItemId");

                    b.ToTable("RiskAssessmentSpecialPermit", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Role", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RoleModule", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationModuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("RoleId", "ApplicationModuleId");

                    b.HasIndex("ApplicationModuleId", "IsActive");

                    b.ToTable("RoleModule", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RoleModuleMenu", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationModuleId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleMenuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("RoleId", "ApplicationModuleId", "ModuleMenuId");

                    b.HasIndex("ApplicationModuleId", "ModuleMenuId", "IsActive");

                    b.ToTable("RoleModuleMenu", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid?>("EntraObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EntraTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfilePicturePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ProfilePictureUpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("EntraTenantId", "EntraObjectId")
                        .IsUnique()
                        .HasFilter("[EntraTenantId] IS NOT NULL AND [EntraObjectId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId", "IsActive");

                    b.ToTable("UserRole", "dbo");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.UserThemeSetting", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Radius")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("UserId");

                    b.ToTable("UserThemeSetting", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_UserThemeSetting_Color", "[Color] IN (N'blue', N'azure', N'indigo', N'purple', N'pink', N'red', N'orange', N'green')");

                            t.HasCheckConstraint("CK_UserThemeSetting_Mode", "[Mode] IN (N'light', N'dark', N'system')");

                            t.HasCheckConstraint("CK_UserThemeSetting_Radius", "[Radius] IN (0, 6, 12)");
                        });
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ApprovalNotification", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.PermitApproval", "PermitApproval")
                        .WithMany("Notifications")
                        .HasForeignKey("PermitApprovalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermitApproval");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Apcloudpms.Domain.Entities.ListItem", "PermitTypeListItem")
                        .WithMany()
                        .HasForeignKey("PermitTypeListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermitTypeListItem");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ApprovalWorkflowLevel", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.Role", "AlternateApproverRole")
                        .WithMany()
                        .HasForeignKey("AlternateApproverRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Apcloudpms.Domain.Entities.ApprovalWorkflow", "ApprovalWorkflow")
                        .WithMany("Levels")
                        .HasForeignKey("ApprovalWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.Role", "PrimaryApproverRole")
                        .WithMany()
                        .HasForeignKey("PrimaryApproverRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlternateApproverRole");

                    b.Navigation("ApprovalWorkflow");

                    b.Navigation("PrimaryApproverRole");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.Department", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.OfficeBranch", "OfficeBranch")
                        .WithMany("Departments")
                        .HasForeignKey("OfficeBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfficeBranch");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ListItem", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.ListItemCategory", "ListItemCategory")
                        .WithMany("ListItems")
                        .HasForeignKey("ListItemCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ListItemCategory");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ModuleMenu", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.ApplicationModule", "ApplicationModule")
                        .WithMany("Menus")
                        .HasForeignKey("ApplicationModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.ModuleMenu", "ParentMenu")
                        .WithMany("Children")
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationModule");

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.OfficeBranch", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.Organization", "Organization")
                        .WithMany("OfficeBranches")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApplication", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.ListItem", "PermitStatusListItem")
                        .WithMany("PermitStatusApplications")
                        .HasForeignKey("PermitStatusListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.ListItem", "PermitTypeListItem")
                        .WithMany("PermitTypeApplications")
                        .HasForeignKey("PermitTypeListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.RiskAssessment", "RiskAssessment")
                        .WithMany("PermitApplications")
                        .HasForeignKey("RiskAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PermitStatusListItem");

                    b.Navigation("PermitTypeListItem");

                    b.Navigation("RiskAssessment");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApplicationConfinedSpace", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.PermitApplication", "PermitApplication")
                        .WithMany("ConfinedSpaces")
                        .HasForeignKey("PermitApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.ListItem", "WorkingInConfinedSpaceListItem")
                        .WithMany("PermitApplicationConfinedSpaces")
                        .HasForeignKey("WorkingInConfinedSpaceListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermitApplication");

                    b.Navigation("WorkingInConfinedSpaceListItem");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApplicationInspectionPriorToComm", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.ListItem", "InspectionPriorToCommListItem")
                        .WithMany("PermitApplicationInspectionsPriorToComm")
                        .HasForeignKey("InspectionPriorToCommListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.PermitApplication", "PermitApplication")
                        .WithMany("InspectionsPriorToComm")
                        .HasForeignKey("PermitApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InspectionPriorToCommListItem");

                    b.Navigation("PermitApplication");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApplicationWallWorks", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.PermitApplication", "PermitApplication")
                        .WithMany("WallWorks")
                        .HasForeignKey("PermitApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.ListItem", "WorksonWallListItem")
                        .WithMany("PermitApplicationWallWorks")
                        .HasForeignKey("WorksonWallListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermitApplication");

                    b.Navigation("WorksonWallListItem");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApproval", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.User", "ActionedByUser")
                        .WithMany()
                        .HasForeignKey("ActionedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Apcloudpms.Domain.Entities.Role", "AlternateApproverRole")
                        .WithMany()
                        .HasForeignKey("AlternateApproverRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Apcloudpms.Domain.Entities.PermitApplication", "PermitApplication")
                        .WithMany("Approvals")
                        .HasForeignKey("PermitApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.Role", "PrimaryApproverRole")
                        .WithMany()
                        .HasForeignKey("PrimaryApproverRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActionedByUser");

                    b.Navigation("AlternateApproverRole");

                    b.Navigation("PermitApplication");

                    b.Navigation("PrimaryApproverRole");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApprovalAssignee", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.PermitApproval", "PermitApproval")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("PermitApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.User", "RevokedByUser")
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Apcloudpms.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("PermitApproval");

                    b.Navigation("RevokedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RiskAssessment", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Apcloudpms.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Apcloudpms.Domain.Entities.ListItem", "RiskAssessmentStatusListItem")
                        .WithMany("RiskAssessmentStatuses")
                        .HasForeignKey("RiskAssessmentStatusListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RiskAssessmentStatusListItem");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RiskAssessmentAdditionalPpe", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.ListItem", "AdditionalProtectiveMeasureListItem")
                        .WithMany("RiskAssessmentAdditionalPpeItems")
                        .HasForeignKey("AdditionalProtectiveMeasuresListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.RiskAssessment", "RiskAssessment")
                        .WithMany("AdditionalPersonalProtectiveEquipment")
                        .HasForeignKey("RiskAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditionalProtectiveMeasureListItem");

                    b.Navigation("RiskAssessment");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RiskAssessmentHazardCategory", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.ListItem", "HazardCategoryListItem")
                        .WithMany("RiskAssessmentHazardCategories")
                        .HasForeignKey("HazardCategoriesListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.RiskAssessment", "RiskAssessment")
                        .WithMany("HazardCategories")
                        .HasForeignKey("RiskAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HazardCategoryListItem");

                    b.Navigation("RiskAssessment");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RiskAssessmentPpe", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.RiskAssessment", "RiskAssessment")
                        .WithMany("PersonalProtectiveEquipment")
                        .HasForeignKey("RiskAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.ListItem", "SpecialPermitListItem")
                        .WithMany("RiskAssessmentPpeItems")
                        .HasForeignKey("SpecialPermitListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RiskAssessment");

                    b.Navigation("SpecialPermitListItem");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RiskAssessmentSpecialPermit", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.RiskAssessment", "RiskAssessment")
                        .WithMany("SpecialPermits")
                        .HasForeignKey("RiskAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.ListItem", "SpecialPermitListItem")
                        .WithMany("RiskAssessmentSpecialPermits")
                        .HasForeignKey("SpecialPermitListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RiskAssessment");

                    b.Navigation("SpecialPermitListItem");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RoleModule", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.ApplicationModule", "ApplicationModule")
                        .WithMany("RoleModules")
                        .HasForeignKey("ApplicationModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.Role", "Role")
                        .WithMany("RoleModules")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationModule");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RoleModuleMenu", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.ModuleMenu", "ModuleMenu")
                        .WithMany("RoleModuleMenus")
                        .HasForeignKey("ApplicationModuleId", "ModuleMenuId")
                        .HasPrincipalKey("ApplicationModuleId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.RoleModule", "RoleModule")
                        .WithMany("RoleModuleMenus")
                        .HasForeignKey("RoleId", "ApplicationModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleMenu");

                    b.Navigation("RoleModule");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.User", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apcloudpms.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.UserThemeSetting", b =>
                {
                    b.HasOne("Apcloudpms.Domain.Entities.User", "User")
                        .WithOne("ThemeSetting")
                        .HasForeignKey("Apcloudpms.Domain.Entities.UserThemeSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ApplicationModule", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("RoleModules");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ListItem", b =>
                {
                    b.Navigation("PermitApplicationConfinedSpaces");

                    b.Navigation("PermitApplicationInspectionsPriorToComm");

                    b.Navigation("PermitApplicationWallWorks");

                    b.Navigation("PermitStatusApplications");

                    b.Navigation("PermitTypeApplications");

                    b.Navigation("RiskAssessmentAdditionalPpeItems");

                    b.Navigation("RiskAssessmentHazardCategories");

                    b.Navigation("RiskAssessmentPpeItems");

                    b.Navigation("RiskAssessmentSpecialPermits");

                    b.Navigation("RiskAssessmentStatuses");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ListItemCategory", b =>
                {
                    b.Navigation("ListItems");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.ModuleMenu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleModuleMenus");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.OfficeBranch", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.Organization", b =>
                {
                    b.Navigation("OfficeBranches");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApplication", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("ConfinedSpaces");

                    b.Navigation("InspectionsPriorToComm");

                    b.Navigation("WallWorks");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.PermitApproval", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RiskAssessment", b =>
                {
                    b.Navigation("AdditionalPersonalProtectiveEquipment");

                    b.Navigation("HazardCategories");

                    b.Navigation("PermitApplications");

                    b.Navigation("PersonalProtectiveEquipment");

                    b.Navigation("SpecialPermits");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleModules");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.RoleModule", b =>
                {
                    b.Navigation("RoleModuleMenus");
                });

            modelBuilder.Entity("Apcloudpms.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("ThemeSetting");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
