// <auto-generated />
using System;
using CleanCrud.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanCrud.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815172733_AddApplicationModulesAndNavigation")]
    partial class AddApplicationModulesAndNavigation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanCrud.Domain.Entities.ApplicationModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("ApplicationModule", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PERMIT",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage permit applications, reviews, and approvals.",
                            DisplayOrder = 1,
                            Icon = "file-check",
                            IsActive = true,
                            Name = "Permit Management System"
                        },
                        new
                        {
                            Id = 2,
                            Code = "VISITOR",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage visitor registration, check-in, and visit history.",
                            DisplayOrder = 2,
                            Icon = "users",
                            IsActive = true,
                            Name = "Visitor Management System"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ASSET",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage organizational assets and assignments.",
                            DisplayOrder = 3,
                            Icon = "package",
                            IsActive = true,
                            Name = "Asset Management System"
                        });
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OfficeBranchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfficeBranchId", "Code")
                        .IsUnique();

                    b.HasIndex("OfficeBranchId", "IsActive");

                    b.ToTable("Department", "dbo");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.ModuleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ApplicationModuleId")
                        .HasColumnType("int");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("int");

                    b.Property<string>("QueryUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ParentMenuId");

                    b.HasIndex("ApplicationModuleId", "QueryUrl")
                        .IsUnique();

                    b.HasIndex("ApplicationModuleId", "IsActive", "DisplayOrder");

                    b.ToTable("ModuleMenu", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionName = "Index",
                            ApplicationModuleId = 1,
                            ControllerName = "PermitDashboard",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Icon = "dashboard",
                            IsActive = true,
                            Name = "Dashboard",
                            QueryUrl = "/api/permit/dashboard"
                        },
                        new
                        {
                            Id = 2,
                            ActionName = "Index",
                            ApplicationModuleId = 1,
                            ControllerName = "PermitApplications",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Icon = "file-text",
                            IsActive = true,
                            Name = "Permit Applications",
                            QueryUrl = "/api/permit/applications"
                        },
                        new
                        {
                            Id = 3,
                            ActionName = "Index",
                            ApplicationModuleId = 1,
                            ControllerName = "PermitApprovals",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Icon = "check-circle",
                            IsActive = true,
                            Name = "Permit Approvals",
                            QueryUrl = "/api/permit/approvals"
                        },
                        new
                        {
                            Id = 4,
                            ActionName = "Index",
                            ApplicationModuleId = 2,
                            ControllerName = "VisitorDashboard",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Icon = "dashboard",
                            IsActive = true,
                            Name = "Dashboard",
                            QueryUrl = "/api/visitor/dashboard"
                        },
                        new
                        {
                            Id = 5,
                            ActionName = "Index",
                            ApplicationModuleId = 2,
                            ControllerName = "VisitorCheckIn",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Icon = "log-in",
                            IsActive = true,
                            Name = "Visitor Check-In",
                            QueryUrl = "/api/visitor/check-in"
                        },
                        new
                        {
                            Id = 6,
                            ActionName = "Index",
                            ApplicationModuleId = 2,
                            ControllerName = "VisitorLog",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Icon = "list",
                            IsActive = true,
                            Name = "Visitor Log",
                            QueryUrl = "/api/visitor/log"
                        },
                        new
                        {
                            Id = 7,
                            ActionName = "Index",
                            ApplicationModuleId = 3,
                            ControllerName = "AssetDashboard",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Icon = "dashboard",
                            IsActive = true,
                            Name = "Dashboard",
                            QueryUrl = "/api/asset/dashboard"
                        },
                        new
                        {
                            Id = 8,
                            ActionName = "Index",
                            ApplicationModuleId = 3,
                            ControllerName = "AssetRegister",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Icon = "archive",
                            IsActive = true,
                            Name = "Asset Register",
                            QueryUrl = "/api/asset/register"
                        },
                        new
                        {
                            Id = 9,
                            ActionName = "Index",
                            ApplicationModuleId = 3,
                            ControllerName = "AssetAssignments",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Icon = "user-check",
                            IsActive = true,
                            Name = "Asset Assignments",
                            QueryUrl = "/api/asset/assignments"
                        });
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.OfficeBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHeadOffice")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsHeadOffice")
                        .IsUnique()
                        .HasFilter("[IsHeadOffice] = 1 AND [IsActive] = 1");

                    b.ToTable("OfficeBranch", "dbo");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("char(64)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("SessionExpiresAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("FamilyId", "RevokedAtUtc");

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Role", "dbo");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.UserModule", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationModuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "ApplicationModuleId");

                    b.HasIndex("ApplicationModuleId", "IsActive");

                    b.ToTable("UserModule", "dbo");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId", "IsActive");

                    b.ToTable("UserRole", "dbo");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.Department", b =>
                {
                    b.HasOne("CleanCrud.Domain.Entities.OfficeBranch", "OfficeBranch")
                        .WithMany("Departments")
                        .HasForeignKey("OfficeBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfficeBranch");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.ModuleMenu", b =>
                {
                    b.HasOne("CleanCrud.Domain.Entities.ApplicationModule", "ApplicationModule")
                        .WithMany("Menus")
                        .HasForeignKey("ApplicationModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanCrud.Domain.Entities.ModuleMenu", "ParentMenu")
                        .WithMany("Children")
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationModule");

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CleanCrud.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.UserModule", b =>
                {
                    b.HasOne("CleanCrud.Domain.Entities.ApplicationModule", "ApplicationModule")
                        .WithMany("UserModules")
                        .HasForeignKey("ApplicationModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanCrud.Domain.Entities.User", "User")
                        .WithMany("UserModules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationModule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("CleanCrud.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanCrud.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.ApplicationModule", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("UserModules");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.ModuleMenu", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.OfficeBranch", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CleanCrud.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserModules");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
